### ISSUE TITLE
Pre-training OcCo

### ISSUE THREAD

**Issue by bachtx12** [hansen7/OcCo#16]
Hi @hansen7 
Firstly, thank you for your code.
Secondly, I have a question about your code pre-training OcCo. I read your code in the completion task (OcCo), these encoders have the same architecture as the encoder of DGCNN or Pointnet classification task. These pre-trained weights are suitable to initialize for the downstream task classification (because they have the same architecture). However, in other downstream tasks such as part segmentation or semantic segmentation, the encoder of these tasks is not the same as the pre-trained weight. Thus, there are some components of the encoder that will be randomly initialized?

Thank you!

**Comment by hansen7** [comment]
Thanks for your notice!

> ..., the encoder of these tasks is not the same as the pre-trained weight. Thus, there are some components of the encoder that will be randomly initialized?

Yes, it is correct. Since the completion decoder is based on a hot code representing each shape, for semseg and partseg encoders, there are certain parameters are randomly initialised at the beginning of fine-tuning.
https://github.com/hansen7/OcCo/blob/c218a2bb446f91702cf8fa6f56bb3a1da406009f/OcCo_Torch/utils/Torch_Utility.py#L17-L33

For the analysis, it is all based on the pre-trained classification encoder (PointNet).
