### ISSUE TITLE
Pre-trained weights for DGCNN

### ISSUE THREAD

**Issue by NCTU-VRDL** [hansen7/OcCo#5]
Hi!

Would you share the weights of DGCNN model? Thank so much!

I am also wondering that why can't I pre-train the model on scanobjectnn dataset?

**Comment by hansen7** [comment]
Hi @NCTU-VRDL, thanks for the interest in our work!

We will release the pre-trained model as well as formalising the test scripts and part segmentation very soon.

One of the reason not to use ScanObjectNN for completion training is because of lack of full object shape therefore it is a bit skeptical to calculate Chamfer distance loss. But it might be useful for downstream tasks as well. You can also take a look at the failed completion objects in readme :)

**Comment by NCTU-VRDL** [comment]
Hi!

Thanks for your reply. I am currently working on a point cloud segmentation project and wish to submit our work to CVPR2021. I hope OcCo pre-training methodology can be included in our experiments. Look forward to the pre-trained model. Thanks so much!

**Comment by NCTU-VRDL** [comment]
Hi @hansen7!

Sorry for bothering you. Is there any updates for the pre-training weights? I only need that for visualization. Thank you:)

**Comment by hansen7** [comment]
Hi @NCTU-VRDL, sorry for the lagging response, will upload by the end of this weekend ;)

**Comment by hansen7** [comment]
Hi @NCTU-VRDL, please see it [here](https://drive.google.com/drive/folders/15H1JH9oTfp_sVkj9nwgnThZHRI9ef2bT?usp=sharing), hope it catches ;)
